# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cbff25ed-6d19-4adf-b13f-e0368695eb69";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/78C1-AF23";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/cbff25ed-6d19-4adf-b13f-e0368695eb69";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/cbff25ed-6d19-4adf-b13f-e0368695eb69";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/cbff25ed-6d19-4adf-b13f-e0368695eb69";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/cbff25ed-6d19-4adf-b13f-e0368695eb69";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/adce610e-28f5-424a-b2c3-23c44945b6b2"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
